[tool.poetry]
name = "src"
version = "0.1.0"
description = "User registration and authentication system with email activation, JWT, and Celery."
authors = ["Your Name <yaroslavsysoiev2000@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.6"
sqlalchemy = "^2.0.36"
pytest = "^8.3.4"
pydantic-settings = "^2.7.0"
pandas = "^2.2.3"
tqdm = "^4.67.1"
uvicorn = "^0.34.0"
httpx = "^0.28.1"
pytest-env = "^1.1.5"
flake8 = "^7.1.1"
aiosqlite = "^0.21.0"
pytest-asyncio = "^0.25.3"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
email-validator = "^2.2.0"
python-jose = {extras = ["cryptography"], version = "^3.5.0"}
asyncpg = "^0.30.0"
psycopg2-binary = "^2.9.10"
aiosmtplib = "^4.0.1"
celery = "^5.5.3"
flower = "^2.0.1"
alembic = "^1.13.1"
redis = "^4.0.0"
jinja2 = "^3.1.2"
aioboto3 = "^12.0.0"
Pillow = "^10.0.0"
python-multipart = "^0.0.9"
validators = "^0.22.0"
beautifulsoup4 = "^4.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dev-dependencies]
black = "^24.4.2"

[tool.black]
line-length = 88
skip-string-normalization = true

[tool.mypy]
python_version = 3.10
ignore_missing_imports = true
strict = false
